name: Deploy to EKS (OIDC)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write       # Needed to request OIDC token
  contents: read        # To checkout repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::571600863856:role/github-eks-oidc-role
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-default-cluster

      - name: Test access
        run: kubectl get nodes
        
